[build]
  base = ""
  publish = "frontend"  # Static files (index.html, home.html, etc.)
  command = "npm install --prefix backend"  # Install backend dependencies
  functions = "netlify/functions"  # Functions folder

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
